services:
  mongodb:
    container_name: fastapi-mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: fastapi_db
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
